Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -59,8 +59,15 @@ jobs:
       - name: Read version from VERSION file
         id: read_version
         run: |
+          if [ -f VERSION ]; then
           VERSION=$(cat go-project/VERSION | xargs)
           echo "VERSION=$VERSION" >> $GITHUB_ENV
+          else
+            echo "VERSION file not found!"
+            exit 1
+          fi
+          # VERSION=$(cat go-project/VERSION | xargs)
+          # echo "VERSION=$VERSION" >> $GITHUB_ENV
           cat go-project/VERSION
 
       - name: Set up Docker Buildx
